version: "3.8"
services:
  frontend-server:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    
  db:
    volumes:
      - ./db_volume:/var/lib/mysql